### ISSUE TITLE
I went wrong when I use the catkin_make to compile the neo_local_planner! 

### ISSUE THREAD

**Issue by yuchuxiang** [neobotix/neo_local_planner#12]
I went wrong when I use the catkin_make to compile the neo_local_planner! 
`neo_local_planner/src/../include/NeoLocalPlanner.h:66:7: error: ‘void neo_local_planner::NeoLocalPlanner::initialize(std::__cxx11::string, tf::TransformListener*, costmap_2d::Costmap2DROS*)’ marked ‘override’, but does not override
  void initialize(std::string name, tf::TransformListener* tf, costmap_2d::Costmap2DROS* costmap_ros) override;
       ^~~~~~~~~~
/home/ycx/neo_local_planner/src/NeoLocalPlanner.cpp: In member function ‘virtual bool neo_local_planner::NeoLocalPlanner::computeVelocityCommands(geometry_msgs::Twist&)’:
/home/ycx/neo_local_planner/src/NeoLocalPlanner.cpp:299:45: error: ‘class base_local_planner::LocalPlannerLimits’ has no member named ‘max_trans_vel’
  const double max_trans_vel = fmax(m_limits.max_trans_vel * (m_max_cost - center_cost) / m_max_cost, m_limits.min_trans_vel);
                                             ^~~~~~~~~~~~~
/home/ycx/neo_local_planner/src/NeoLocalPlanner.cpp:299:111: error: ‘class base_local_planner::LocalPlannerLimits’ has no member named ‘min_trans_vel’
 s.max_trans_vel * (m_max_cost - center_cost) / m_max_cost, m_limits.min_trans_vel);
                                `

**Comment by padhupradheep** [comment]
Thanks for reporting. Could you please let me know the following details:

- ROS-Distro you use
- Branch that is in use

**Comment by yuchuxiang** [comment]
Oh,sorry,maybe i used the wrong branch!compile passed!thank for your fast reply!

**Comment by padhupradheep** [comment]
feel free to close the problem, if you do not face any issues.
