### ISSUE TITLE
backward motion enable

### ISSUE THREAD

**Issue by roboticsai** [neobotix/neo_local_planner#8]
Is their any easy way in which neo_local_planner can make given diff drive robot move backward also? As i studied the source code, in line number 431 their is a line which looks like it can control the backward motion also but is not working when commented out and tested:
```
		// only allow forward velocity in this branch
		control_vel_x = fmax(control_vel_x, 0);
```

**Comment by madMAx43v3r** [comment]
To allow backwards driving you have to set `max_backup_dist` to zero, which means infinite backwards distance allowed. By default it's only 0.1 m. But keep in mind there is no scanner stop when going backwards with MP-400.

**Comment by padhupradheep** [comment]
Closing the issue, because of no further activity. Feel free to re-open the issue, if there is anyother questions!
